### ISSUE TITLE
convert the caffe to ckpt

### ISSUE THREAD

**Issue by mingminzhen** [DrSleep/tensorflow-deeplab-resnet#104]
I download the model from deeplab repo. I use the init.caffemodel in the zip files.
Then i run the convert.py. Errors occurs:

Traceback (most recent call last):
  File "./convert.py", line 61, in <module>
    main()
  File "./convert.py", line 57, in main
    args.phase)
  File "./convert.py", line 28, in convert
    transformer = TensorFlowTransformer(def_path, caffemodel_path, phase=phase)
  File "/tensorflow-deeplab-resnet/kaffe/tensorflow/transformer.py", line 221, in __init__
    self.load(def_path, data_path, phase)
  File "Documents/tensorflow-deeplab-resnet/kaffe/tensorflow/transformer.py", line 227, in load
    graph = GraphBuilder(def_path, phase).build()
  File "Documents/tensorflow-deeplab-resnet/kaffe/graph.py", line 140, in __init__
    self.load()
  File "Documents/tensorflow-deeplab-resnet/kaffe/graph.py", line 144, in load
    self.params = get_caffe_resolver().NetParameter()
  File "Documents/tensorflow-deeplab-resnet/kaffe/caffe/resolver.py", line 32, in get_caffe_resolver
    SHARED_CAFFE_RESOLVER = CaffeResolver()
  File "Documents/tensorflow-deeplab-resnet/kaffe/caffe/resolver.py", line 7, in __init__
    self.import_caffe()
  File "Documents/tensorflow-deeplab-resnet/kaffe/caffe/resolver.py", line 17, in import_caffe
    from . import caffepb
  File "Documents/tensorflow-deeplab-resnet/kaffe/caffe/caffepb.py", line 28, in <module>
    type=None),
  File "/usr/lib64/python2.7/site-packages/google/protobuf/descriptor.py", line 649, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

**Comment by DrSleep** [comment]
this is related to this repository - https://github.com/ethereon/caffe-tensorflow.
