### ISSUE TITLE
ResourceExhaustedError:: OOM when allocating tensor with shape[360,2048,9,9]

### ISSUE THREAD

**Issue by luoxiaoliaolan** [DrSleep/tensorflow-deeplab-resnet#114]
As I try to train on the PASCAL VOC dataset, I received this error:
/……
s: 6.99GiB
I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                  7573333607
InUse:                  7505581568
MaxInUse:               7525589248
NumAllocs:                    5453
MaxAllocSize:           2991302144

W tensorflow/core/common_runtime/bfc_allocator.cc:274] **********************************************************************************************xxxxxx
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 720.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[5760,2048,4,4]
Traceback (most recent call last):
  File "train.py", line 253, in <module>
    main()
  File "train.py", line 242, in main
    loss_value, images, labels, preds, summary, _ = sess.run([reduced_loss, image_batch, label_batch, pred, total_summary, train_op], feed_dict=feed_dict)
  File "/home/precision/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/precision/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/precision/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/precision/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[360,2048,9,9]
	 [[Node: fc1_voc12_c0/atrous_conv2d = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fc1_voc12_c0/atrous_conv2d/SpaceToBatchND, fc1_voc12_c0/weights/read)]]
	 [[Node: add/_1171 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_7454_add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'fc1_voc12_c0/atrous_conv2d', defined at:
  File "train.py", line 253, in <module>
    main()
  File "train.py", line 144, in main
    net = DeepLabResNetModel({'data': image_batch}, is_training=args.is_training, num_classes=args.num_classes)
  File "/home/precision/code/tensorflow-deeplab-resnet-master/kaffe/tensorflow/network.py", line 48, in __init__
    self.setup(is_training, num_classes)
  File "/home/precision/code/tensorflow-deeplab-resnet-master/deeplab_resnet/model.py", line 402, in setup
    .atrous_conv(3, 3, num_classes, 6, padding='SAME', relu=False, name='fc1_voc12_c0'))
  File "/home/precision/code/tensorflow-deeplab-resnet-master/kaffe/tensorflow/network.py", line 22, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/precision/code/tensorflow-deeplab-resnet-master/kaffe/tensorflow/network.py", line 173, in atrous_conv
    output = convolve(input, kernel)
  File "/home/precision/code/tensorflow-deeplab-resnet-master/kaffe/tensorflow/network.py", line 168, in <lambda>
    convolve = lambda i, k: tf.nn.atrous_conv2d(i, k, dilation, padding=padding)
  File "/home/precision/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 994, in atrous_conv2d
    name=name)
  File "/home/precision/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 396, in conv2d
    data_format=data_format, name=name)
  File "/home/precision/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/precision/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/precision/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

 ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[360,2048,9,9]
	 [[Node: fc1_voc12_c0/atrous_conv2d = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fc1_voc12_c0/atrous_conv2d/SpaceToBatchND, fc1_voc12_c0/weights/read)]]
	 [[Node: add/_1171 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_7454_add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
In train.py  batch_size is 10
I guess its my GPU problem. So I try to reduced it ,and It did not work until 7.But when batch_size is 7, its loss has been around 1.2 range shock, didn't converge, I can't get the training model.How to solve this problem?
By the way， my GPU's momery is 8G.

**Comment by DrSleep** [comment]
reduce batch size or use train_msc with gradient accumulation. Check if your training set is correct.

**Comment by ChulhoonJang** [comment]
@DrSleep

I stuck with the same problem. The loss didn't go down below 1.2 until over 8000 steps.

In my case, the GPU has 4 GB memory, so I am trying to train the model with XEON CPU + 32GB RAM.

The trained data is described as below
![individualimage2](https://user-images.githubusercontent.com/13134640/32163260-162a63b6-bd9f-11e7-83e0-706e6fc141be.png)
left: source image, center: gt image, right: inference image obtained by the model (8000 steps)


I tried various batch sizes from 1 to 10 and different learning rates from 2.5e-3 to 2.5e-5. It failed.

Could you give any guides or instructions to reduce the loss?
