### ISSUE TITLE
Variable "any variable"/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

### ISSUE THREAD

**Issue by seanchung2** [DrSleep/tensorflow-deeplab-resnet#127]
I tried your npy2ckpt.py to convert all the numpy weights I have and none of them can be converted successfully. They all come up with the message below:
> ValueError: Variable [_**depends on which  .npy**_]/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

I even tried to use your convert.py to get the .npy file but they are still in vain. Can anyone please tell me how to solve this? Thanks!

The following is the message result from trying to convert VGG16.npy
```

2017-10-15 20:21:16.896526: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-15 20:21:16.896579: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-15 20:21:16.896586: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-15 20:21:16.896591: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-15 20:21:16.896595: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "npy2ckpt.py", line 69, in <module>
    main()
  File "npy2ckpt.py", line 62, in main
    net.load(args.npy_path, sess)
  File "~/tensorflow-deeplab-resnet/kaffe/tensorflow/network.py", line 65, in load
    var = tf.get_variable(param_name)
  File "/home/parallels/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/parallels/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/parallels/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/parallels/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/parallels/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 682, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable conv5_1/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

```

**Comment by DrSleep** [comment]
`npy2ckpt` assumes that the underlying model is DeepLab-ResNet: there is no `conv5_1` in DeepLab
