### ISSUE TITLE
OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)

### ISSUE THREAD

**Issue by abel-w** [DrSleep/tensorflow-deeplab-resnet#150]
thanks for your geat work. I encount the follow problem when I run the code , thank you very much.

D:\Anaconda3\python.exe "D:\PyCharm Community Edition 2017.2.3\helpers\pydev\pydev_run_in_console.py" 51787 51788 D:/pyprojects/tensorflow-deeplab-resnet-master/train.py
Running D:/pyprojects/tensorflow-deeplab-resnet-master/train.py
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['D:\\pyprojects\\tensorflow-deeplab-resnet-master', 'D:/pyprojects/tensorflow-deeplab-resnet-master'])
Backend Qt5Agg is interactive backend. Turning interactive mode on.
2017-12-10 14:58:35.976057: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-12-10 14:58:35.976473: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-10 14:58:35.976857: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-10 14:58:35.977247: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-10 14:58:35.977635: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-10 14:58:35.978033: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-12-10 14:58:35.978417: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-10 14:58:35.978802: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-12-10 14:58:42.310260: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Can not get size for: ./dataset/VOCdevkit/SegmentationClassAug/2008_003519.png : ϵͳ�Ҳ���ָ����·����
2017-12-10 14:58:42.310260: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Can not get size for: ./dataset/VOCdevkit/JPEGImages/2008_003519.jpg : ϵͳ�Ҳ���ָ����·����
--- Logging error ---
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1063, in _single_operation_run
    target_list_as_strings, status, None)
  File "D:\Anaconda3\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Can not get size for: ./dataset/VOCdevkit/SegmentationClassAug/2008_003519.png : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
	 [[Node: create_inputs/ReadFile_1 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/input_producer/Gather_1)]]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\logging\__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcd5' in position 195: surrogates not allowed
Call stack:
  File "D:\Anaconda3\lib\threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "D:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\queue_runner_impl.py", line 254, in _run
    coord.request_stop(e)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\coordinator.py", line 222, in request_stop
    compat.as_str_any(ex))
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\platform\tf_logging.py", line 82, in info
    _logger.info(msg, *args, **kwargs)
Message: 'Error reported to Coordinator: %s, %s'
Arguments: (<class 'tensorflow.python.framework.errors_impl.NotFoundError'>, 'Can not get size for: ./dataset/VOCdevkit/SegmentationClassAug/2008_003519.png : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3\r\n\n\t [[Node: create_inputs/ReadFile_1 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/input_producer/Gather_1)]]')
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
  File "D:\Anaconda3\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\PyCharm Community Edition 2017.2.3\helpers\pydev\pydev_run_in_console.py", line 37, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm Community Edition 2017.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/pyprojects/tensorflow-deeplab-resnet-master/train.py", line 254, in <module>
    main()
  File "D:/pyprojects/tensorflow-deeplab-resnet-master/train.py", line 243, in main
    sess.run([reduced_loss, image_batch, label_batch, pred, total_summary, train_op], feed_dict=feed_dict)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
Caused by op 'create_inputs/batch', defined at:
  File "D:\PyCharm Community Edition 2017.2.3\helpers\pydev\pydev_run_in_console.py", line 82, in <module>
    globals = run_file(file, None, None)
  File "D:\PyCharm Community Edition 2017.2.3\helpers\pydev\pydev_run_in_console.py", line 37, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm Community Edition 2017.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/pyprojects/tensorflow-deeplab-resnet-master/train.py", line 254, in <module>
    main()
  File "D:/pyprojects/tensorflow-deeplab-resnet-master/train.py", line 141, in main
    image_batch, label_batch = reader.dequeue(args.batch_size)
  File "D:/pyprojects/tensorflow-deeplab-resnet-master\deeplab_resnet\image_reader.py", line 179, in dequeue
    num_elements)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\input.py", line 919, in batch
    name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\training\input.py", line 716, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 457, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 946, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()
OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

**Comment by xhw205** [comment]
I have the same problem.Are you solve it?

**Comment by Z-Ianthe** [comment]
I have the same problem！！Are you solve it?

**Comment by xhw205** [comment]
I solve this problem，and after training I used the saved model to predict，the outputs image are all black.I don't know why，just follow the author's ReadMe.md.

**Comment by abel-w** [comment]
the problem was solved, thank everyone above.
the problem will solved if you change the paths of file in the file 'train.txt' to your own paths.
thanks again!!

**Comment by xhw205** [comment]
I used the voc2012, but after training ,all of the outputs image are black!!! Im crazy .......

**Comment by Z-Ianthe** [comment]
I have changed the paths of file in the file 'train.txt' to my own paths, but "2008_003519.png" does not exist in the voc2012.  The version I downloaded is VOCtrainval_11-May-2012.tar

**Comment by Z-Ianthe** [comment]
No. I just download the already converted models.

**Comment by sunbin1205** [comment]
@abel-w 
**hello,can you help me to solve this erro??thank you very much!**
python train.py 
2018-01-26 08:38:03.548643: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-26 08:38:03.548682: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-26 08:38:03.548690: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-01-26 08:38:03.548695: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-26 08:38:03.548699: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-01-26 08:38:03.560712: E tensorflow/stream_executor/cuda/cuda_driver.cc:405] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-01-26 08:38:03.560762: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: zbw-System-Product-Name
2018-01-26 08:38:03.560772: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: zbw-System-Product-Name
2018-01-26 08:38:03.560806: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 387.26.0
2018-01-26 08:38:03.560833: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.90  Tue Sep 19 19:17:35 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
"""
2018-01-26 08:38:03.560852: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 384.90.0
2018-01-26 08:38:03.560861: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:303] kernel version 384.90.0 does not match DSO version 387.26.0 -- cannot find working devices in this configuration
Restored model parameters from ./deeplab_resnet.ckpt
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    main()
  File "train.py", line 244, in main
    loss_value, images, labels, preds, summary, _ = sess.run([reduced_loss, image_batch, label_batch, pred, total_summary, train_op], feed_dict=feed_dict)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 2, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

Caused by op u'create_inputs/batch', defined at:
  File "train.py", line 255, in <module>
    main()
  File "train.py", line 141, in main
    image_batch, label_batch = reader.dequeue(args.batch_size)
  File "/media/Linux/sun/Segmentation/building_segmentation/deeplab_resnet/image_reader.py", line 179, in dequeue
    num_elements)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 917, in batch
    name=name)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 712, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1328, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/zbw/anaconda2/envs/sun/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 2, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
**we can see that the dataset can be loaded normally, Does that mean that I have the right path to the train.txt file? So what's the problem?Looking forward to your reply!**
