### ISSUE TITLE
Error happen when training

### ISSUE THREAD

**Issue by zhang-qiang-github** [DrSleep/tensorflow-deeplab-resnet#155]
When I train my data, error happens after 23 step:

...
step 18 	 loss = 12.353, (0.685 sec/step)
step 19 	 loss = 24.190, (0.685 sec/step)
step 20 	 loss = 25.551, (0.692 sec/step)
step 21 	 loss = 10.660, (0.679 sec/step)
step 22 	 loss = 44.417, (0.680 sec/step)
step 23 	 loss = 34.889, (0.695 sec/step)
Traceback (most recent call last):
  File "/home/zhq4/tensorflow-deeplab-resnet-master/train.py", line 255, in <module>
    main()
  File "/home/zhq4/tensorflow-deeplab-resnet-master/train.py", line 248, in main
    loss_value, _ = sess.run([reduced_loss, train_op], feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[9092] = -1077198781 is not in [0, 13448)
	 [[Node: Gather = Gather[Tindices=DT_INT64, Tparams=DT_UINT8, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Reshape_1/_1515, Squeeze/_1517)]]

Caused by op u'Gather', defined at:
  File "/home/zhq4/tensorflow-deeplab-resnet-master/train.py", line 255, in <module>
    main()
  File "/home/zhq4/tensorflow-deeplab-resnet-master/train.py", line 172, in main
    gt = tf.cast(tf.gather(raw_gt, indices), tf.int32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 2486, in gather
    params, indices, validate_indices=validate_indices, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1834, in gather
    validate_indices=validate_indices, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[9092] = -1077198781 is not in [0, 13448)
	 [[Node: Gather = Gather[Tindices=DT_INT64, Tparams=DT_UINT8, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Reshape_1/_1515, Squeeze/_1517)]]

2018-01-05 12:51:55.402370: E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_DEINITIALIZED
2018-01-05 12:51:55.402407: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:203] Unexpected Event status: 1

what's the possible error?

**Comment by zhang-qiang-github** [comment]
Actually, it turn out my environment rise this error.

**Comment by sunbin1205** [comment]
@zhang-qiang-github HOW can you train you own dataset?can you tell me?such as,the step to make your own data to be the formate as voc2012?
