### ISSUE TITLE
Restore called with invalid save path

### ISSUE THREAD

**Issue by weigq** [DrSleep/tensorflow-deeplab-resnet#28]
I`m new here.
I just follow the steps, and all the requirements are met, when I run:
```python train.py --random-scale```
I get this:
```
xxx@imcl-test:/data/xxx/deeplab/tensorflow-deeplab-resnet$ python train.py --random-scale
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: Tesla K40m
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:06:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:06:00.0)
Traceback (most recent call last):
  File "train.py", line 189, in <module>
    main()
  File "train.py", line 168, in main
    load(loader, sess, args.restore_from)
  File "train.py", line 85, in load
    saver.restore(sess, ckpt_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1342, in restore
    "File path is: %r" % (save_path, file_path))
ValueError: Restore called with invalid save path: './deeplab_resnet.ckpt'. File path is: './deeplab_resnet.ckpt'
```

what should I do?
thanks!

**Comment by weigq** [comment]
@DrSleep

**Comment by DrSleep** [comment]
@weigq, seems like you don't have the deeplab_resnet.ckpt file. 
You can either download it or explicitly change the default value of 'restore from' to None.

**Comment by weigq** [comment]
it works 
thanks
