### ISSUE TITLE
W tensorflow/core/framework/op_kernel.cc:968]

### ISSUE THREAD

**Issue by weigq** [DrSleep/tensorflow-deeplab-resnet#38]
I have download the VOC2012 from [here](https://pjreddie.com/projects/pascal-voc-dataset-mirror/)  
and I run this script:
```
python train.py --random-scale
```

but i encounter the following error:
```
XXX@imcl-test:/data/XXX/deeplab/tensorflow-deeplab-resnet$ python train.py --random-scale
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: Tesla K40m
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:06:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:06:00.0)
Restored model parameters from ./deeplab_resnet.ckpt



#### this is the error


W tensorflow/core/framework/op_kernel.cc:968] Not found: ./VOCdevkit/JPEGImages/2009_004475.jpg
W tensorflow/core/framework/op_kernel.cc:968] Not found: ./VOCdevkit/SegmentationClassAug/2009_004475.png
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueMany[_class=["loc:@create_inputs/batch/fifo_queue"], component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueMany[_class=["loc:@create_inputs/batch/fifo_queue"], component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
Traceback (most recent call last):
  File "train.py", line 192, in <module>
    main()
  File "train.py", line 181, in main
    loss_value, images, labels, preds, summary, _ = sess.run([reduced_loss, image_batch, label_batch, pred, total_summary, optim])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueMany[_class=["loc:@create_inputs/batch/fifo_queue"], component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

Caused by op u'create_inputs/batch', defined at:
  File "train.py", line 192, in <module>
    main()
  File "train.py", line 106, in main
    image_batch, label_batch = reader.dequeue(args.batch_size)
  File "/data/weigq/deeplab/tensorflow-deeplab-resnet/deeplab_resnet/image_reader.py", line 103, in dequeue
    num_elements)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 597, in batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 905, in _queue_dequeue_many
    timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueMany[_class=["loc:@create_inputs/batch/fifo_queue"], component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]


```

who can help me 
thanks Ｔ_Ｔ

**Comment by DrSleep** [comment]
Please make sure that these paths do exist
./VOCdevkit/JPEGImages/2009_004475.jpg and
./VOCdevkit/SegmentationClassAug/2009_004475.png
If not, you would need to download the dataset following the links in README

**Comment by weigq** [comment]
thanks first

I have install the VOC2012 from ```http://host.robots.ox.ac.uk/pascal/VOC/voc2012/```
and the folder is : 

```
XXX@imcl-test:/data/XXX/deeplab/tensorflow-deeplab-resnet$ cd ./VOCdevkit/
XXX@imcl-test:/data/XXX/deeplab/tensorflow-deeplab-resnet/VOCdevkit$ ls
create_segmentations_from_detections.m  example_action.m       example_classifier.m  example_layout.m     local    viewanno.m  VOC2012
devkit_doc.pdf                          example_action_nobb.m  example_detector.m    example_segmenter.m  results  viewdet.m   VOCcode
XXX@imcl-test:/data/XXX/deeplab/tensorflow-deeplab-resnet/VOCdevkit$ cd ./VOC2012/
XXX@imcl-test:/data/XXX/deeplab/tensorflow-deeplab-resnet/VOCdevkit/VOC2012$ ls
Annotations  ImageSets  JPEGImages  SegmentationClass  SegmentationObject

```

but there are not : 
```
./VOCdevkit/JPEGImages/2009_004475.jpg and
./VOCdevkit/SegmentationClassAug/2009_004475.png
```

**Comment by weigq** [comment]
why i dont have the SegmentationClassAug

**Comment by DrSleep** [comment]
Please download this archive as well: https://www.dropbox.com/s/oeu149j8qtbs1x0/SegmentationClassAug.zip?dl=0

**Comment by weigq** [comment]
thanks very much!!!!!
I`ve solved the problem.
