### ISSUE TITLE
W tensorflow/core/framework/op_kernel.cc:1152] Not found

### ISSUE THREAD

**Issue by Yaredoh** [DrSleep/tensorflow-deeplab-resnet#79]
Hi,

What is the reason this error is happening ? 

Restored model parameters from ./deeplab_resnet.ckpt
2017-05-05 15:23:06.615207: W tensorflow/core/framework/op_kernel.cc:1152] Not found: /home/VOCdevkit/SegmentationClassAug/2008_003519.png
2017-05-05 15:23:06.615207: W tensorflow/core/framework/op_kernel.cc:1152] Not found: /home/VOCdevkit/JPEGImages/2008_003519.jpg
Traceback (most recent call last):
  File "train.py", line 253, in <module>
    main()
  File "train.py", line 242, in main
    loss_value, images, labels, preds, summary, _ = sess.run([reduced_loss, image_batch, label_batch, pred, total_summary, train_op], feed_dict=feed_dict)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

Caused by op u'create_inputs/batch', defined at:
  File "train.py", line 253, in <module>
    main()
  File "train.py", line 141, in main
    image_batch, label_batch = reader.dequeue(args.batch_size)
  File "/home/yared/tensorflow-deeplab-resnet-master/deeplab_resnet/image_reader.py", line 179, in dequeue
    num_elements)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 917, in batch
    name=name)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 712, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1328, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

**Comment by DrSleep** [comment]
First, please check that the files can indeed be found on those paths: 

> 2017-05-05 15:23:06.615207: W tensorflow/core/framework/op_kernel.cc:1152] Not found: /home/VOCdevkit/SegmentationClassAug/2008_003519.png
> 2017-05-05 15:23:06.615207: W tensorflow/core/framework/op_kernel.cc:1152] Not found: /home/VOCdevkit/JPEGImages/2008_003519.jpg

**Comment by Yaredoh** [comment]
I downloaded the VOCdevkit file and placed it in Home directory. But, didn't found it. could this be related with the tensorflow version? I am using tensorflow  1.1 and python 2.7 .

**Comment by DrSleep** [comment]
If you cannot find the dataset, then this is the problem.
TF and python versions are not related to it.

**Comment by Yaredoh** [comment]
**Thanks, for your response. It can read load the image. but, it can't read the mask/label. The file is there i checked it but it can't load it. I don't know why?**

Restored model parameters from ./deeplab_resnet.ckpt
2017-05-06 23:04:46.554659: W tensorflow/core/framework/op_kernel.cc:1152] Not found: /home/yared/Desktop/pro/annot/image(27).png
Traceback (most recent call last):
  File "train.py", line 254, in <module>
    main()
  File "train.py", line 243, in main
    loss_value, images, labels, preds, summary= sess.run([reduced_loss, image_batch, label_batch, pred, total_summary, train_op], feed_dict=feed_dict)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

Caused by op u'create_inputs/batch', defined at:
  File "train.py", line 254, in <module>
    main()
  File "train.py", line 141, in main
    image_batch, label_batch = reader.dequeue(args.batch_size)
  File "/home/yared/tensorflow-deeplab-resnet-master1/deeplab_resnet/image_reader.py", line 179, in dequeue
    image_batch, label_batch = tf.train.batch([self.image, self.label], num_elements)
File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 917, in batch
    name=name)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 712, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1328, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

**Comment by Yaredoh** [comment]
It stars training and stops and brings the error ...

Restored model parameters from deeplab_resnet.ckpt
2017-05-07 12:55:25.806612: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Unknown: NewRandomAccessFile failed to Create/Open: pro : Access is denied.
; Input/output error
2017-05-07 12:55:25.806612: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Unknown: NewRandomAccessFile failed to Create/Open: pro : Access is denied.
; Input/output error
2017-05-07 12:55:26.647734: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.94GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-05-07 12:55:26.728924: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.59GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-05-07 12:55:26.790851: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.59GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-05-07 12:55:26.839325: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.85GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-05-07 12:55:26.868058: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.88GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
The checkpoint has been created.
step 0   loss = 4.713, (13.539 sec/step)
step 1   loss = 3.497, (0.669 sec/step)
2017-05-07 12:55:39.661197: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Out of range: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 2, current size 1)
         [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

**Comment by DrSleep** [comment]
Seems like some files from the list cannot be read. Make sure that path to the files in the list are valid.
Regarding the labels, it looks like you are not using VOC dataset: if that is the case, you need to have the format of your segmentation masks coinciding with the format of the VOC images as per the DeepLab setup (i.e., without a colour map).

**Comment by ZhengtianXu** [comment]
@DrSleep Images in 'SegmentationClassAug' are already labelled? Every pixel in each image is in the range of 20?

**Comment by DrSleep** [comment]
Already labelled. <= 20 and 255 (the 'void' label)

**Comment by Yaredoh** [comment]
My RGB label is just like this. And i configured it on utils.py ... is there any other place also do i have to modify?   

Impervious surfaces (RGB: 255, 255, 255)
Building (RGB: 0, 0, 255)
Low vegetation (RGB: 0, 255, 255)
Tree (RGB: 0, 255, 0)
Car (RGB: 255, 255, 0)
Clutter/background (RGB: 255, 0, 0)

**Comment by DrSleep** [comment]
You need to convert RGB vectors into 1-D labels: e.g., Background -> 0, Car
-> 1, and etc.

**Comment by DrSleep** [comment]
> Please take a look here: https://github.com/martinkersner/train-DeepLab#data-conversions (the second paragraph).
> Also this function should be useful to perform the conversion: https://github.com/martinkersner/train-DeepLab/blob/master/utils.py#L91

**Comment by Yaredoh** [comment]
Thank you, DrSleep. I think that is why the labeled image is not loading. I will look at it.

**Comment by Yaredoh** [comment]
Hello DrSleep,
This code is converts to 2D labels? We can not used it for 1-D convert ?

`def convert_from_color_segmentation(arr_3d):
    arr_2d = np.zeros((arr_3d.shape[0], arr_3d.shape[1]), dtype=np.uint8)

    for c, i in palette.items():
        m = np.all(arr_3d == np.array(c).reshape(1, 1, 3), axis=2)
        arr_2d[m] = i

    return arr_2d`

**Comment by DrSleep** [comment]
It converts to a 2d array (array of pixels), where each value is a 1-d
label. The code that I linked can be used without a problem.

**Comment by Yaredoh** [comment]
Thanks. I will use it.

**Comment by Yaredoh** [comment]
python fine_tune.py --not-restore-last

`BATCH_SIZE = 4
DATA_DIRECTORY = '/home/yared/Desktop/tensorflow-deeplab-resnet-master/dataset'
DATA_LIST_PATH = 'dataset/train_tf.txt'
IGNORE_LABEL = 255
INPUT_SIZE = '1000,1000'
LEARNING_RATE = 1e-4
NUM_CLASSES = 6
NUM_STEPS = 20000
RANDOM_SEED = 1234
RESTORE_FROM = 'deeplab_resnet.ckpt'
SAVE_NUM_IMAGES = 2
SAVE_PRED_EVERY = 100
SNAPSHOT_DIR = './snapshots_finetune/'`

Label shape
`
np.array(Image.open('dataset/annot/image(1).png')).shape

(1000, 1000)`

Train_tf.txt

`/images/image(1).png /annot/image(1).png 
/images/image(3).png /annot/image(3).png 
/images/image(5).png /annot/image(5).png 
/images/image(7).png /annot/image(7).png 
/images/image(9).png /annot/image(9).png
/images/image(11).png /annot/image(11).png 
/images/image(13).png /annot/image(13).png
/images/image(15).png /annot/image(15).png 
/images/image(17).png /annot/image(17).png 
/images/image(19).png /annot/image(19).png 
/images/image(21).png /annot/image(21).png
/images/image(23).png /annot/image(23).png 
/images/image(25).png /annot/image(25).png 
/images/image(27).png /annot/image(27).png
/images/image(29).png /annot/image(29).png `


I converted all the label files to 1D with ..

`palette = {(255,255,255) : 0 ,
         (0,0, 255) : 1 ,
         (0,255,0) : 2,
           (0,255,255) : 3,
           ( 255,255,0) : 4,
           (255,0,0) : 5
           
          }
def convert_from_color_segmentation(arr_3d):
    arr_2d = np.zeros((arr_3d.shape[0], arr_3d.shape[1]), dtype=np.uint8)

    for c, i in palette.items():
        m = np.all(arr_3d == np.array(c).reshape(1, 1, 3), axis=2)
        arr_2d[m] = i

    return arr_2d

for l_f in tqdm(label_files):
    arr = np.array(Image.open(label_dir + l_f))
    arr_2d = convert_from_color_segmentation(arr)
    Image.fromarray(arr_2d).save(new_label_dir + l_f)

`

error : I gave it 4 batch it considers only two.

`tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 2, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

Caused by op u'create_inputs/batch', defined at:
  File "fine_tune.py", line 207, in <module>
    main()
  File "fine_tune.py", line 125, in main
    image_batch, label_batch = reader.dequeue(args.batch_size)
  File "/home/yared/Desktop/tensorflow-deeplab-resnet-master/deeplab_resnet/image_reader.py", line 179, in dequeue
    num_elements)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 917, in batch
    name=name)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 712, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1328, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/yared/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 2, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

`
Please, could you check my dataset? Let me sent you by email. What is wrong with it.

**Comment by Yaredoh** [comment]
I understand the problem now. The way I generated the data list was wrong. That was the problem. 

`## we want /train/file1.png /labels_tf/file1.png
with open('dataset/train_tf.txt', 'w+') as f:
    for el in trn_lst:
        el = el.decode('utf-8')[:-5]
        f.write('/images/{}.png /annot/{}.png\n'.format(el, el))
`

I should have to use the above code to generate my data list. That is why it was not reading it.  Thanks for your information.

**Comment by sunbin1205** [comment]
@Yaredoh 
Hello, did you make your own data set of voc format? Have you successfully trained?
