### ISSUE TITLE
evaluate.py doesn't work

### ISSUE THREAD

**Issue by ldenoue** [DrSleep/tensorflow-deeplab-resnet#80]
I ran this: python3 inference.py /tmp/iphone.jpg deeplab_resnet.ckpt 
But here's the traceback I get:

Traceback (most recent call last):
  File "inference.py", line 104, in <module>
    main()
  File "inference.py", line 67, in main
    net = DeepLabResNetModel({'data': tf.expand_dims(img, dim=0)}, is_training=False, num_classes=args.num_classes)
  File "/Users/denoue/examples/segmentation/tensorflow-deeplab-resnet/kaffe/tensorflow/network.py", line 48, in __init__
    self.setup(is_training, num_classes)
  File "/Users/denoue/examples/segmentation/tensorflow-deeplab-resnet/deeplab_resnet/model.py", line 20, in setup
    .conv(7, 7, 64, 2, 2, biased=False, relu=False, name='conv1')
  File "/Users/denoue/examples/segmentation/tensorflow-deeplab-resnet/kaffe/tensorflow/network.py", line 22, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/Users/denoue/examples/segmentation/tensorflow-deeplab-resnet/kaffe/tensorflow/network.py", line 128, in conv
    kernel = self.make_var('weights', shape=[k_h, k_w, c_i / group, c_o])
TypeError: unsupported operand type(s) for /: 'Dimension' and 'int'

**Comment by DrSleep** [comment]
Have not tested it on python3, only python 2.7.

**Comment by georkap** [comment]
working on python 3.5. 
from line:  kernel = self.make_var('weights', shape=[k_h, k_w, c_i / group, c_o])
I cast c_i to int(c_i) and it works
